
neptune_security:
    resource: '@ScyLabsNeptuneBundle/Resources/config/routing/security.yaml'
neptune:
    resource: "@ScyLabsNeptuneBundle/Resources/config/routes.yaml"
    prefix: /admin
neptune_front:
    resource: "@ScyLabsNeptuneBundle/Resources/config/routes_front.yaml"

    